version: "2"
services:
  web:
    build: ./docker/php5.6-apache
    container_name: web
    ports:
      - "8000:80"
    links:
      - db:db
    volumes:
      - ./web:/var/www/test/web
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: szhajdu
      MYSQL_PASSWORD: password
    volumes:
      - ./cache:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"